services:
  catalogdb:
    image: postgres
    container_name: catalogdb
    environment:
      POSTGRES_DB: CatalogDb  # Change to CatalogDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
